// Audit actions — mirrors SEC §17.1. A test (ADV-X04) fails if the two lists differ.

export const AUDIT_ACTIONS = [
  // Identity & membership
  'MEMBER_INVITED',
  'INVITATION_REVOKED',
  'INVITATION_ACCEPTED',
  'ROLE_CHANGED',
  'MEMBER_DISABLED',
  'MEMBER_ENABLED',
  'MEMBER_REMOVED',
  'USER_DISABLED',
  // Guards & devices
  'GUARD_CREATED',
  'GUARDS_BULK_IMPORTED',
  'GUARD_UPDATED',
  'GUARD_DISABLED',
  'GUARD_TERMINATED',
  'DEVICE_ENROLLMENT_CODE_ISSUED',
  'DEVICE_REGISTERED',
  'DEVICE_REVOKED',
  'TRACKING_CONSENT_RECORDED',
  // Sites & patrols
  'SITE_CREATED',
  'SITE_UPDATED',
  'GEOFENCE_CHANGED',
  'CHECKPOINT_CREATED',
  'CHECKPOINT_UPDATED',
  'CHECKPOINT_QR_ROTATED',
  'CHECKPOINT_QR_PRINTED',
  'PATROL_ROUTE_CREATED',
  'PATROL_ROUTE_UPDATED',
  // Shifts
  'SHIFT_CREATED',
  'SHIFTS_BULK_CREATED',
  'SHIFT_UPDATED',
  'SHIFT_REASSIGNED',
  'SHIFT_CANCELLED',
  'SHIFT_MANUAL_START',
  'SHIFT_FORCE_ENDED',
  'SHIFT_EXTENDED',
  'SHIFT_REOPENED',
  // Location
  'LOCATION_HISTORY_VIEWED',
  'LOCATION_HISTORY_EXPORTED',
  'LOCATION_REPORT_VIEWED',
  // Incidents
  'INCIDENT_CREATED',
  'INCIDENT_UPDATED',
  'INCIDENT_STATUS_CHANGED',
  'ATTACHMENT_ORIGINAL_DOWNLOADED',
  // Alerts & SOS
  'ALERT_ACKNOWLEDGED',
  'ALERT_RESOLVED',
  'ALERT_DISMISSED',
  'SOS_VIEWED',
  'SOS_ACKNOWLEDGED',
  'SOS_RESOLVED',
  'SOS_DRILL_STARTED',
  'SOS_DRILL_ENDED',
  // Organization
  'ORGANIZATION_CREATED',
  'SETTINGS_CHANGED',
  'EXPORT_REQUESTED',
  'EXPORT_DOWNLOADED',
  'RETENTION_RUN',
  'PLATFORM_ACCESS',
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
