-- 0001_foundation.sql
-- Extensions, the tenant-context helper and the organizations table.
-- Runs as `migrator`, which owns every table (ARCH §4.3). RLS is ENABLED, not FORCED (D-33):
-- the runtime roles never own tables, so RLS binds them, while data migrations run by the owner
-- are not silently filtered to zero rows.

create extension if not exists btree_gist;
create extension if not exists citext;
create extension if not exists pgcrypto;

-- Nobody but the owner creates objects; runtime roles only use them.
revoke create on schema public from public;
grant usage on schema public to app_runtime, system_worker, retention_worker;
grant select on schema_migrations to app_runtime;

create schema app;
revoke all on schema app from public;
grant usage on schema app to app_runtime, system_worker, retention_worker;

-- The tenant context every RLS policy reads. NULLIF matters: once a pooled connection has used
-- the setting, current_setting() returns '' instead of NULL, and ''::uuid would raise an error
-- (review M-01, confirmed on PostgreSQL 17 during Phase 0). A missing context yields NULL, so
-- policies match no rows: fail closed.
create function app.current_org_id() returns uuid
  language sql
  stable
  as $$ select nullif(current_setting('app.org_id', true), '')::uuid $$;

revoke execute on function app.current_org_id() from public;
grant execute on function app.current_org_id() to app_runtime, system_worker, retention_worker;

-- ARCH §6.3. IDs are UUIDv7 generated by the API (review A-08), so there is no default here.
create table organizations (
  id uuid primary key,
  name text not null check (char_length(name) between 1 and 120),
  legal_name text check (char_length(legal_name) <= 200),
  status text not null default 'ACTIVE' check (status in ('ACTIVE', 'SUSPENDED', 'CLOSED')),
  timezone text not null check (char_length(timezone) between 1 and 64),
  default_locale text not null default 'en' check (default_locale in ('en', 'ur')),
  data_region text not null check (char_length(data_region) between 1 and 64),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table organizations enable row level security;

-- A request sees only its own organization.
create policy organizations_runtime_read on organizations
  for select to app_runtime
  using (id = app.current_org_id());

grant select on organizations to app_runtime;
