// Generates src/generated/db.ts (Kysely table types, D-10) from a freshly migrated database.
// `--check` fails if the committed file differs, so the types can never describe an older schema.
import { spawn } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import pg from 'pg';

import { bootstrapRoles } from '../src/roles.ts';
import { startCluster } from '../test-support/cluster.ts';
import { createTestDatabase } from '../test-support/database.ts';

const OUT = fileURLToPath(new URL('../src/generated/db.ts', import.meta.url));
const require = createRequire(import.meta.url);
const manifestPath = require.resolve('kysely-codegen/package.json');
const manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as { bin: Record<string, string> };
const BIN = join(dirname(manifestPath), manifest.bin['kysely-codegen'] ?? '');

const check = process.argv.includes('--check');
const cluster = await startCluster();
let failed = false;
try {
  const admin = new pg.Client({ connectionString: cluster.adminUrl });
  await admin.connect();
  await bootstrapRoles(admin);
  await admin.end();

  const db = await createTestDatabase(cluster.adminUrl);
  const scratch = await mkdtemp(join(tmpdir(), 'sentryops-codegen-'));
  try {
    const target = join(scratch, 'db.ts');
    const code = await new Promise<number>((resolve) => {
      const child = spawn(
        process.execPath,
        [
          BIN,
          '--dialect',
          'postgres',
          '--url',
          db.urls.migrator,
          '--out-file',
          target,
          '--log-level',
          'error',
        ],
        { stdio: 'inherit' },
      );
      child.on('close', (c) => resolve(c ?? 1));
    });
    if (code !== 0) throw new Error(`kysely-codegen exited with ${code}`);
    const generated = `// Generated by packages/db/scripts/codegen.ts (kysely-codegen). Do not edit; run \`pnpm db:codegen\`.\n${await readFile(target, 'utf8')}`;

    if (check) {
      let committed = '';
      try {
        committed = readFileSync(OUT, 'utf8');
      } catch {
        // missing counts as stale
      }
      if (committed !== generated) {
        console.error('✗ packages/db/src/generated/db.ts is stale. Run `pnpm db:codegen`.');
        failed = true;
      } else {
        console.log('✓ generated database types match the migrated schema');
      }
    } else {
      writeFileSync(OUT, generated);
      console.log('wrote packages/db/src/generated/db.ts');
    }
  } finally {
    await rm(scratch, { recursive: true, force: true });
    await db.drop();
  }
} finally {
  await cluster.stop();
}
if (failed) process.exit(1);
